<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DummyDataSeeder extends Seeder
{
    public function run()
    {
        for ($i=1; $i<=6; $i++) {
            DB::table('blogs')->insert([
                'title' => "Advanced Architecture Principles $i", 
                'slug' => "advanced-architecture-principles-$i", 
                'snippet' => "A brief overview of enterprise integration.",
                'content' => "This is comprehensive testing data for the blog post $i generated by the seeding script. It simulates a long-form technical article.", 
                'status'=>'published'
            ]);
            DB::table('casestudies')->insert([
                'client' => "Corp Solutions Inc. Phase $i", 
                'title' => "Migrated Legacy Tech Debt $i",
                'challenge' => "The company was facing a critical infrastructural bottleneck.",
                'solution' => "We rebuilt everything perfectly using modern scalable tools.",
                'result' => "Over 400% performance boost."
            ]);
            DB::table('portfolio')->insert([
                'title' => "Alpha Project $i",
                'description' => "An intricate web 3.0 dashboard and analytics platform.",
                'techStack' => "React, Laravel, AWS"
            ]);
            DB::table('testimonials')->insert([
                'name' => "John Doe $i", 
                'text' => "Tafinity completely transformed our business operations. The team is exceptional and delivery was faster than expected! Testimonial entry $i.", 
                'role'=> "CTO", 
                'rating'=>5
            ]);
            DB::table('jobs')->insert([
                'title' => "Senior Role Tier $i", 
                'type' => "Full-time",
                'location' => "Remote",
                'salary' => "15 LPA",
                'description' => "We are looking for a highly capable engineer $i. Responsibilities include building scalable APIs."
            ]);
            DB::table('internships')->insert([
                'title' => "Summer Intern Wave $i",
                'track' => "Software Engineering",
                'duration' => "3 Months",
                'startDate' => "Immediate",
                'syllabus' => "Learn React, Node, Laravel, and advanced CI/CD."
            ]);
        }
    }
}
